---
- name: Install notepad++
  win_chocolatey:
    name: notepadplusplus
    state: present

- name: Create local admin
  win_user:
    name: admin
    password: "xxx"
    groups: ["Administrators"]
    