---
- name: Install Windows Server 2016 Containers feature
  win_feature:
    name: Containers # required. Names of roles or features to install as a single feature or a comma-separated list of features.
    include_sub_features: yes # not required. Adds all subfeatures of the specified feature.
    state: present # not required. choices: present;absent. State of the features or roles on the system.

- name: Removed unused Windows features
  win_feature:
    name: 
    - FS-SMB1 
    - Web-Server 
    - Windows-Defender-Features
    state: absent


- name: Add a DockerMsftProvider powershell module and register a repository
  win_psmodule:
    name: DockerMsftProvider
    repository: PSGallery
    state: present

- win_shell: Install-Package -Name docker -ProviderName DockerMsftProvider

- win_shell: Restart-Computer -Force