---
- name: Install notepad++
  win_chocolatey:
    name: notepadplusplus
    state: present

- name: Removed unused Windows features
  win_feature:
    name: 
    - FS-SMB1
    state: absent

- name: Create local admin
  win_user:
    name: "{{ Windows_Local_Admin_USERNAME }}"
    password: "{{ Windows_Local_Admin_PASSWORD }}"
    groups: ["Administrators"]
    