---
- name: Install notepad++
  win_chocolatey:
    name: notepadplusplus
    state: present

- name: Create local admin
  win_user:
    name: {{Windows_Local_Admin_USERNAME}}
    password: "{{Windows_Local_Admin_PASSWORD}}"
    groups: ["Administrators"]
    